[project]
name = "vllm-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub>=0.36.0",
    "streamlit>=1.53.1",
    "torch>=2.9.1",
    "vllm>=0.14.1",
]
